baseURL = 'http://jimolonely.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh-cn"
title = 'JIMO POWER'
theme = "compose"
#theme = "hugo-coder"

# 配置菜单
[[languages.zh-cn.menu.main]]
name = "JDK源码无坚不摧"
weight = 10
url = "jdk/"

[[languages.zh-cn.menu.main]]
name = "算法升天之路"
weight = 20
url = "algo/"

[[languages.zh-cn.menu.main]]
name = "大数据算什么"
weight = 30
url = "bigdata/"

[[languages.zh-cn.menu.main]]
name = "云计算只是开始"
weight = 40
url = "cloud/"
