baseURL = 'http://jimolonely.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh-cn"
title = 'jimolonely power'
theme = "hugo-coder"

# 配置菜单
[[languages.zh-cn.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.zh-cn.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.zh-cn.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.zh-cn.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"
