baseURL = 'https://jimolonely.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh"
title = 'JIMO POWER'
theme = "ananke"
disqusShortname = "jimolonely"

SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-111673440-1"
enableRobotsTXT = true

[languages]
[languages.zh]
title = "孤独的寂寞"
weight = 1
contentDir = "content/zh"
#[languages.en]
#title = "JIMO POWER"
#weight = 5
#contentDir = "content/en"
#[languages.fr]
#title = "JIMO POWER"
#weight = 10
#contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
env = "production"
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "我很强，遇强则强"
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 5
# Hugo的日期格式也是奇葩，必须是2006年1月2日3时4分5秒
date_format = "2006-01-02"
body_classes = "avenir bg-transparent "
#commentoEnable = true
custom_css = ["jimo.css"]


[[params.ananke_socials]]
name = "github"
url = "https://github.com/jimolonely"

[markup]
defaultMarkdownHandler = 'blackfriday'
[markup.blackFriday]
hrefTargetBlank = true