baseURL = 'http://jimolonely.github.io/'
languageCode = 'zh-cn'
defaultContentLanguage = "zh"
title = 'JIMO POWER'
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-111673440-1"
enableRobotsTXT = true

[languages]
[languages.zh]
title = "孤独的寂寞"
weight = 1
contentDir = "content/zh"
[languages.en]
title = "JIMO POWER"
weight = 5
contentDir = "content/en"
[languages.fr]
title = "JIMO POWER"
weight = 10
contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
env = "production"
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "我很强，遇强则强"
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 5

[[params.ananke_socials]]
name = "github"
url = "https://github.com/jimolonely"

[markup]
defaultMarkdownHandler = 'blackfriday'
[markup.blackFriday]
hrefTargetBlank = true